// Shared fleet vehicle data — used by both the listing page and dynamic detail pages.

export type VehicleCategory = "sedan" | "suv" | "van" | "luxury" | "bus";

export interface FleetVehicle {
  slug: string;
  name: string;
  subtitle: string;
  category: VehicleCategory;
  passengers: number;
  luggage: number;
  startingPrice: number;
  badge: string;
  rating: number;
  reviews: number;
  image: string;
  features: string[];
  description: string;
}

export const FLEET_VEHICLES: FleetVehicle[] = [
  {
    slug: "toyota-camry",
    name: "Toyota Camry",
    subtitle: "Executive Sedan",
    category: "sedan",
    passengers: 4,
    luggage: 2,
    startingPrice: 80,
    badge: "Best Value",
    rating: 4.9,
    reviews: 312,
    image: "https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=900&q=80",
    features: ["Premium Air Conditioning", "English & Arabic Chauffeur", "USB Charging", "Complimentary Water"],
    description: "The go-to choice for city transfers and airport runs. Smooth, reliable, and impeccably maintained.",
  },
  {
    slug: "gmc-yukon-xl",
    name: "GMC Yukon XL",
    subtitle: "Premium SUV",
    category: "suv",
    passengers: 7,
    luggage: 5,
    startingPrice: 150,
    badge: "Most Popular",
    rating: 4.9,
    reviews: 278,
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=80",
    features: ["Individual Climate Control", "Premium Leather Cabin", "Extra Legroom", "Panoramic Sunroof"],
    description: "Spacious luxury SUV perfect for families, groups, and VIP transfers across Saudi Arabia.",
  },
  {
    slug: "hyundai-staria",
    name: "Hyundai Staria",
    subtitle: "VIP Van",
    category: "van",
    passengers: 7,
    luggage: 4,
    startingPrice: 130,
    badge: "Family Pick",
    rating: 4.8,
    reviews: 189,
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=900&q=80",
    features: ["Multi-Zone AC", "Panoramic Windows", "Reclining Seats", "Family Friendly"],
    description: "A revolutionary luxury van with futuristic design and premium cabin comfort for the whole family.",
  },
  {
    slug: "cadillac-escalade",
    name: "Cadillac Escalade",
    subtitle: "Elite SUV",
    category: "suv",
    passengers: 7,
    luggage: 4,
    startingPrice: 200,
    badge: "Elite Choice",
    rating: 4.9,
    reviews: 145,
    image: "https://images.unsplash.com/photo-1601929862074-04b7b88f0c82?auto=format&fit=crop&w=900&q=80",
    features: ["38-Speaker AKG Audio", "Night Vision System", "Curved OLED Display", "Massaging Seats"],
    description: "American luxury at its finest. An icon of prestige for executive travel and VIP arrivals.",
  },
  {
    slug: "mercedes-s-class",
    name: "Mercedes S-Class",
    subtitle: "Ultra Luxury",
    category: "luxury",
    passengers: 3,
    luggage: 2,
    startingPrice: 250,
    badge: "VIP Choice",
    rating: 5.0,
    reviews: 201,
    image: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=900&q=80",
    features: ["Burmester 4D Audio", "MBUX Hyperscreen", "Massage Seat Package", "Ambient Lighting 64 Colors"],
    description: "The benchmark of automotive luxury. Reserve for the most discerning executives and dignitaries.",
  },
  {
    slug: "bmw-7-series",
    name: "BMW 7 Series",
    subtitle: "Executive Luxury",
    category: "luxury",
    passengers: 3,
    luggage: 2,
    startingPrice: 230,
    badge: "Executive Class",
    rating: 4.9,
    reviews: 167,
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=900&q=80",
    features: ["Bowers & Wilkins Diamond Audio", "Sky Lounge Roof", "Executive Rear Lounge", "BMW Live Cockpit"],
    description: "Sheer driving pleasure meets opulent rear-cabin refinement. The ultimate executive sedan.",
  },
  {
    slug: "genesis-g80",
    name: "Genesis G80",
    subtitle: "Premium Sedan",
    category: "sedan",
    passengers: 3,
    luggage: 2,
    startingPrice: 180,
    badge: "Premium Value",
    rating: 4.8,
    reviews: 134,
    image: "https://images.unsplash.com/photo-1603386329225-868f9b1ee6c9?auto=format&fit=crop&w=900&q=80",
    features: ["Lexicon Audio", "Power Reclining Seats", "Heated & Ventilated Seats", "Advanced ADAS"],
    description: "Korean luxury sophistication — an understated, refined choice for business class transfers.",
  },
  {
    slug: "ford-taurus",
    name: "Ford Taurus",
    subtitle: "Business Sedan",
    category: "sedan",
    passengers: 3,
    luggage: 2,
    startingPrice: 100,
    badge: "Business Class",
    rating: 4.7,
    reviews: 223,
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=900&q=80",
    features: ["Ford SYNC System", "Adaptive Cruise Control", "Premium Leather Seats", "Power Moonroof"],
    description: "A solid business-class sedan offering comfort and reliability for corporate travel in KSA.",
  },
  {
    slug: "mercedes-vito",
    name: "Mercedes Vito",
    subtitle: "Business Van",
    category: "van",
    passengers: 7,
    luggage: 4,
    startingPrice: 160,
    badge: "Corporate Pick",
    rating: 4.8,
    reviews: 156,
    image: "https://images.unsplash.com/photo-1567416661576-659de24d4344?auto=format&fit=crop&w=900&q=80",
    features: ["Executive Captain Seats", "Dark Privacy Glass", "Fold-Down Tables", "Conference Setup"],
    description: "Executive transport for corporate groups. Configured for business with fold-down work tables.",
  },
  {
    slug: "mercedes-sprinter",
    name: "Mercedes Sprinter",
    subtitle: "Corporate Van",
    category: "van",
    passengers: 14,
    luggage: 4,
    startingPrice: 300,
    badge: "Group Leader",
    rating: 4.8,
    reviews: 98,
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=900&q=80",
    features: ["VIP Lounge Layout", "Individual Reading Lights", "PA System", "Luggage Compartment"],
    description: "For groups up to 14. Conference-style or lounge seating — ideal for corporate roadshows.",
  },
  {
    slug: "hyundai-starex",
    name: "Hyundai Starex",
    subtitle: "Family Van",
    category: "van",
    passengers: 7,
    luggage: 10,
    startingPrice: 140,
    badge: "Pilgrim Favorite",
    rating: 4.7,
    reviews: 412,
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=80",
    features: ["Extra Luggage Space", "Dual AC Zones", "Foldable 3rd Row", "Pilgrimage Ready"],
    description: "Trusted by pilgrims and families alike. Exceptional cargo space for Umrah & Hajj journeys.",
  },
  {
    slug: "toyota-hiace",
    name: "Toyota Hiace",
    subtitle: "Group Transport",
    category: "bus",
    passengers: 11,
    luggage: 16,
    startingPrice: 280,
    badge: "Reliable Workhorse",
    rating: 4.7,
    reviews: 267,
    image: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=900&q=80",
    features: ["High-Roof Spacious Cabin", "Captain Seats", "Central AC", "Long-Distance Comfort"],
    description: "Saudi Arabia's most trusted group transport. Ideal for Umrah pilgrim groups and corporate trips.",
  },
  {
    slug: "toyota-coaster",
    name: "Toyota Coaster",
    subtitle: "Corporate Bus",
    category: "bus",
    passengers: 17,
    luggage: 20,
    startingPrice: 500,
    badge: "Fleet Standard",
    rating: 4.8,
    reviews: 178,
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=900&q=80",
    features: ["Plush Reclining Seats", "Entertainment Screen", "Luggage Bay", "Climate Controlled"],
    description: "The benchmark coach for Saudi corporate fleets, Umrah operators, and large group movements.",
  },
  {
    slug: "luxury-bus",
    name: "Luxury Coach Bus",
    subtitle: "Large Groups",
    category: "bus",
    passengers: 25,
    luggage: 30,
    startingPrice: 800,
    badge: "Grand Fleet",
    rating: 4.9,
    reviews: 89,
    image: "https://images.unsplash.com/photo-1464219789935-c2d9d9aba644?auto=format&fit=crop&w=900&q=80",
    features: ["Full Sound System", "LED Ambient Lighting", "Restroom Onboard", "WiFi Connected"],
    description: "Our grandest vehicle for weddings, large pilgrim groups, and full-day corporate tours.",
  },
];
