export type BlogLocale = "en" | "ar";

export const BLOG_STRINGS = {
  en: {
    blog: "Blog",
    home: "Home",
    eyebrow: "Travel & transport guides",
    indexH1: "Saudi Arabia Transport & Travel Guides",
    indexLead:
      "Practical, route-specific guides for travellers moving around the Kingdom — airport arrivals, intercity drives, Umrah logistics, AlUla, business trips and events. Written to help you plan, not to sell you a ride.",
    indexFacts: ["Fares quoted & agreed before booking", "English- & Arabic-speaking drivers", "Free cancellation up to 24h before pickup"],
    featured: "Featured guide",
    all: "All",
    articles: "articles",
    readTime: (m: number) => `${m} min read`,
    published: "Published",
    updated: "Updated",
    by: "By",
    quickAnswer: "Quick answer",
    toc: "In this guide",
    planTrip: "Plan this trip",
    planTripLead: "Pages with the details, vehicles and booking options for this journey.",
    related: "Related guides",
    readArticle: "Read guide",
    backToBlog: "All guides",
    ctaHeading: "Ask for your fare",
    ctaText:
      "Tell us your pickup, destination, date and group size. We reply with a fixed fare you agree before booking — no meter, no surge.",
    whatsapp: "Get a quote on WhatsApp",
    rfq: "Email a corporate RFQ",
    callRecovery: "Call the recovery line",
    indexCtaHeading: "Know your route already?",
    indexCtaText: "Send the details and get a fixed fare confirmed before you book.",
    indexCtaButton: "Request a transfer quote",
    browseRoutes: "Browse routes",
    noPosts: "No guides in this category yet.",
    dateLocale: "en-GB",
    invoicing: "Corporate invoicing can be arranged through our sister company.",
  },
  ar: {
    blog: "المدونة",
    home: "الرئيسية",
    eyebrow: "أدلة السفر والتنقل",
    indexH1: "أدلة التنقل والسفر في المملكة العربية السعودية",
    indexLead:
      "أدلة عملية مخصّصة لكل مسار لمن يتنقّل داخل المملكة — الوصول إلى المطارات، الرحلات بين المدن، ترتيبات العمرة، العُلا، رحلات العمل والفعاليات. هدفها مساعدتك على التخطيط قبل أي شيء آخر.",
    indexFacts: ["السعر يُتّفق عليه قبل الحجز", "سائقون يتحدثون العربية والإنجليزية", "إلغاء مجاني حتى 24 ساعة قبل الموعد"],
    featured: "دليل مميّز",
    all: "الكل",
    articles: "مقالات",
    readTime: (m: number) => `${m} ${m >= 3 && m <= 10 ? "دقائق" : "دقيقة"} قراءة`,
    published: "نُشر",
    updated: "حُدّث",
    by: "بقلم",
    quickAnswer: "الإجابة المختصرة",
    toc: "محتويات الدليل",
    planTrip: "خطّط لرحلتك",
    planTripLead: "صفحات فيها تفاصيل الرحلة وفئات السيارات وطريقة الحجز.",
    related: "أدلة ذات صلة",
    readArticle: "اقرأ الدليل",
    backToBlog: "كل الأدلة",
    ctaHeading: "اطلب سعر رحلتك",
    ctaText: "أرسل لنا نقطة الانطلاق والوجهة والتاريخ وعدد الركاب، ونرد عليك بسعر ثابت تتفق عليه قبل الحجز — بدون عدّاد وبدون زيادة مفاجئة.",
    whatsapp: "اطلب السعر عبر واتساب",
    rfq: "أرسل طلب عرض سعر للشركات",
    callRecovery: "اتصل بخط السحب",
    indexCtaHeading: "هل تعرف مسارك؟",
    indexCtaText: "أرسل التفاصيل واحصل على سعر ثابت مؤكد قبل الحجز.",
    indexCtaButton: "اطلب عرض سعر للتوصيل",
    browseRoutes: "تصفّح المسارات",
    noPosts: "لا توجد أدلة في هذا التصنيف بعد.",
    dateLocale: "ar-SA-u-ca-gregory",
    invoicing: "يمكن ترتيب الفواتير للشركات عبر شركتنا الشقيقة.",
  },
} as const;

export function formatDate(iso: string, locale: BlogLocale) {
  return new Date(`${iso}T00:00:00Z`).toLocaleDateString(BLOG_STRINGS[locale].dateLocale, {
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });
}
